### ISSUE TITLE
Docker 数据不能持久化，数据卷挂到本地报错

### ISSUE THREAD

**Issue by lyy289065406** [Tencent/bk-cmdb#5770]
### 问题描述

docker 环境启动不了。
因为不想配置的测试数据丢失，把数据卷挂载出来了。

- 结果前端报错  `rewrite request failed, oops, there is no topo can be used`
- 进入 docker 执行  `/data/down.sh && /data/run.sh`，报错：`{"result":false,"bk_error_code":1105000,"bk_error_msg":"迁移数据失败, server selection error: server selection timeout\ncurrent topology: Type: ReplicaSetNoPrimary\nServers:\nAddr: localhost:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection(localhost:27017[-501]) connection is closed\n","permission":null,"data":null}`

判断是无法读写数据库。

------

### 重现方法

docker-compose.yml 配置文件如下：

```yml
version: '3.1'
services:
  cmdb:
    image: ccr.ccs.tencentyun.com/bk.io/cmdb-standalone:latest
    container_name: bk_cmdb
    hostname: BK_CMDB
    volumes:
      - ./data/mongodb:/data/sidecar/mongodb/db
      - ./data/redis:/data/sidecar/redis/db
      - ./data/zookeeper:/data/sidecar/zookeeper/data
      - ./logs/mongodb:/data/sidecar/mongodb/log
      - ./logs/redis:/data/sidecar/redis/log
      # - ./logs/zookeeper:/data/sidecar/zookeeper/log
    networks: 
      vpn:
        ipv4_address: 172.168.33.2
    ports:
      - "8090:8090"
    restart: on-failure

networks:
  vpn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.168.33.0/24
          gateway: 172.168.33.1
```

执行 `docker-compose up -d` 启动
