### ISSUE TITLE
模型批量导入导出功能

### ISSUE THREAD

**Issue by chalice-1831** [Tencent/bk-cmdb#6034]
### 概要

1. 模型本身数据体量较小，不超过1mb的数据，任务采用同步方式，在事务下进行
2. 仅新增模型，已存在的模型校验到会进行拒绝并返回
3. 导入时文件传输仅需要传一次
4. 后台接到文件进行校验，使判断有无密码以及提供的密码是否正确，不正确则返回，之后解包校验文件内容，返回全量数据
5. 前端提交批量导入的数据，后台进行校验，无误后插入db，遇错截断返回
6. 导出仅根据前端提供参数从db拉取并组合导出
7. 文件格式使用yaml，压缩文件为zip
8. 后端使用的压缩加解密方法基于第三方开源包github.com/yeka/zip并对其进行了少量的修改，加密方案为AES256，解密则允许压缩包为zipcrypto加密方式或aes128、aes192、aes256加密方式
9. 单模型单文件
10. 有效期考虑写在每个模型yaml上
11. 有效期：有效期标识采用一个单独的字段进行记录并对其进行加密，校验时会对其进行解密然后判断结果。生成的有效期是根据当前时间加上参数中的有效期限得到的过期时间，每次加密的key都设置为当前的导出时间，导出时间也会作为字段保存在yaml中

#### 导入

1. 拿到压缩包后判断是否加密，加密没提供密码直接返回。解压后校验文件类型以及关键字，全量返回文件内容给前端。
2. 前端传递需要导入的内容参数，检验数据合法性后循环写入db，返回结果（业务下执行）

#### 导出

1. 导出接口，需要导出的模型id，需要导出的模型默认会将其所有关联关系导出，如果仅需导出特定的关联关系需要提供对应关联的id
2. 导出还需要提供密码，有效期，文件名这三个参数，密码二次校验由前端进行确认。
3. 导出失败重试需要前端重新传递参数。

#### 导入

上传文件

```json
// 入参
url: "/object/importmany/analysis"
request:{
  "password":"1234567"
}
response: 
// 成功
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": "",
    "permission": null,
    "data": {
        "import_object": [
            {
                "bk_obj_id": "testObj1",
                "bk_obj_name": "测试模型1",
                "bk_obj_icon": "icon-cc-default",
                "ispre": false,
                "bk_classification_id": "bk_network",
                "bk_classification_name": "网络",
                "object_asst": [
                    {
                        "bk_obj_asst_id": "testObj1_belong_bk_switch",
                        "bk_obj_asst_name": "",
                        "bk_obj_id": "",
                        "bk_asst_obj_id": "bk_switch",
                        "bk_asst_obj_name": "交换机",
                        "bk_asst_id": "belong",
                        "mapping": "n:n",
                        "bk_asst_obj_icon": "icon-cc-switch2",
                        "bk_asst_obj_ispre": false
                    }
                ],
                "object_attr": [
                    {
                        "bk_property_id": "bk_inst_name",
                        "bk_property_name": "实例名",
                        "bk_property_group": "default",
                        "bk_property_group_name": "Default",
                        "bk_property_index": 0,
                        "unit": "",
                        "placeholder": "",
                        "editable": true,
                        "isrequired": true,
                        "isreadonly": false,
                        "isonly": true,
                        "bk_property_type": "singlechar",
                        "option": null,
                        "description": ""
                    }
                ]
            }
        ],
        "import_asst": [
            {
                "bk_asst_id": "test",
                "bk_asst_name": "测试",
                "src_des": "测试",
                "dest_des": "被测试",
                "direction": "src_to_dest"
            }
        ]
    }
}
// 失败
{
  	"result": false,
    "bk_error_code": 1234567,
    "bk_error_msg": "password verification failed/file type verification failed/validity period timed out/....",
    "permission": null,
}
```

批量新增

```json
url:"/object/importmany"
request: {
    "import_object": [
            {
                "bk_obj_id": "testObj1",
                "bk_obj_name": "测试模型1",
                "bk_obj_icon": "icon-cc-default",
                "ispre": false,
                "bk_classification_id": "bk_network",
                "bk_classification_name": "网络",
                "object_asst": [
                    {
                        "bk_obj_asst_id": "testObj1_belong_bk_switch",
                        "bk_obj_asst_name": "",
                        "bk_obj_id": "",
                        "bk_asst_obj_id": "bk_switch",
                        "bk_asst_obj_name": "交换机",
                        "bk_asst_id": "belong",
                        "mapping": "n:n",
                        "bk_asst_obj_icon": "icon-cc-switch2",
                        "bk_asst_obj_ispre": false
                    }
                ],
                "object_attr": [
                    {
                        "bk_property_id": "bk_inst_name",
                        "bk_property_name": "实例名",
                        "bk_property_group": "default",
                        "bk_property_group_name": "Default",
                        "bk_property_index": 0,
                        "unit": "",
                        "placeholder": "",
                        "editable": true,
                        "isrequired": true,
                        "isreadonly": false,
                        "isonly": true,
                        "bk_property_type": "singlechar",
                        "option": null,
                        "description": ""
                    }
                ]
            }
        ],
        "import_asst": [
            {
                "bk_asst_id": "test",
                "bk_asst_name": "测试",
                "src_des": "测试",
                "dest_des": "被测试",
                "direction": "src_to_dest"
            }
        ]
}

response:
// 成功
{
    "result": true,
    "bk_error_code": 0,
    "bk_error_msg": "success",
    "permission": null,
  	"data": null
}

// 失败
{
    "result": false,
    "bk_error_code": 1234567,
    "bk_error_msg": "bk_switch attribute operator import error ...",
    "permission": null,
    "data": null
}
```

#### 导出

```json
url:"/object/exportmany"
{
  "object_id":[11,12,13],				//需要导出的模型对应的id
  "excluded_asst_id":[4,5,6],		//不需要导出的模型关联关系id
  "password":"1234567",					//文件密码，没有则为免密
  "expiration":7,								//文件有效期，单位为天，无限期为0
  "file_name":"export_file"     //文件名
}
```

#### 文件结构示例

yaml:

```yaml
// object
creator: admin
createTime: 202206241533
expireTime: NheI/JanSmIHL4D14QcjQA==
object:
  - bk_classification_id: bk_network
    bk_classification_name: 网络
    bk_obj_id: bk_switch
    bk_obj_icon: icon-cc-switch2
    bk_obj_name: 交换机
    bk_ispre: false
    object_attr:
      - isrequired: true,
        bk_obj_id: bk_switch,
        bk_property_type: singlechar,
        bk_property_id: bk_asset_id,
        bk_property_name: 固资编号,
        bk_property_group: default,
        bk_property_group_name: 基础信息,
        bk_property_index: 1,
        editable: false,
        ispre: true,
        bk_isapi: false,
        option: '',
        bk_biz_id: 0,
        description: ''
    object_asst:
      - bk_obj_asst_id: bk_switch_belong_test
        bk_obj_asst_name: ''
        bk_asst_obj_id: test
        bk_asst_obj_name: 测试
        bk_asst_obj_icon: "icon-cc-default"
        bk_asst_obj_ispre: false
        bk_asst_id: belong
        mapping: 'n:n'
        
// association
creator: admin
createTime: 202206241533
expireTime: NheI/JanSmIHL4D14QcjQA==
asst:
  - direction: src_to_dest
    ispre: true
    bk_asst_id: connect
    bk_asst_name: 上联
    src_des: 上联
    dest_des: 下联

```
