### ISSUE TITLE
feat: redis支持TLS连接

### ISSUE THREAD

**Issue by yuyudeqiu** [Tencent/bk-cmdb#8379]
### 功能需求背景

部分安全性要求较高的场景，redis的连接需要使用使用 tls 连接。

### 解决方案

**涉及的修改如下**：

- 抽离 `apimachinery/util` 中的 TLSClientConfig，解决import cycle
  - 抽离 TLSClientConfig  到 `common/ssl`
  - 修改引用处
- redis 客户端增加 TLS 配置
  - redis 客户端
- redisstore 客户端
  - 构建客户端函数参数支持 TLS
  - webserver 调用 redisstore 部分增加传入 tls 参数
- viper 读取配置增加读取 TLS 配置
- ini.py 初始化配置脚本增加 TLS 配置
- Helm chart 增加配置
  - 增加证书 configmap
  - values.yaml 增加证书路径
  - 依赖 redis 服务 的 deployment 挂载 证书 configmap

#### 1. 抽离配置

如果直接复用 `configcenter/src/apimachinery/util` 的 TLSClientConfig 结构体，但是直接使用这里会有一个 import cycle 问题：

```sh
package configcenter/src/scene_server/admin_server
	imports configcenter/src/scene_server/admin_server/app from migrate.go
	imports configcenter/src/ac/iam from server.go
	imports configcenter/src/apimachinery from iam.go
	imports configcenter/src/apimachinery/adminserver from clientset.go
	imports configcenter/src/apimachinery/rest from adminserver.go
	imports configcenter/src/apimachinery/util from client.go
	imports configcenter/src/common/backbone/configcenter from type.go
	imports configcenter/src/storage/dal/mongo from viper.go
	imports configcenter/src/storage/dal from config.go
	imports configcenter/src/storage/dal/redis from dal.go
	imports configcenter/src/apimachinery/util from redis.go: import cycle not allowed
```

主要问题在于它的 NewTLSClientConfigFromConfig 方法依赖了 `configcenter/src/common/backbone/configcenter`，`configcenter/src/common/backbone/configcenter` 又间接地依赖了 `configcenter/src/storage/dal/redis`。需要调整这部分结构台代码的位置，以及调整对这个struct 引用部分的代码。

这里的思路是，解除 redis 对 `configcenter/src/apimachinery/util` 的依赖，将 TLSClientConfig 抽离出来，放到 `configcenter/src/common/ssl` 中，redis 和 `apimachinery/util/type.go` 等地方，修改应用 `configcenter/src/common/ssl` 的 TLSClientConfig，经过验证可以解决 import cycle 问题

另外 `configcenter/src/common/ssl` 中的工具方法，没有一个可以适配多种情况的方法，比如只有 caFile 则只读取 caFile 初始化 tls.Config；如果 certFile 和 keyFile 也不为空，则读取这3个文件初始化 tls.Config。

因为 redis 的 ssl 支持 两种方式包括单向 tls 只需要使用cafile，以及双向tls，还需要提供 cerfFile 和 keyFile 所以这里增加了一个函数用来初始化，根据路径是否填写来初始化特定的 tls.Config：

```go
func NewTLSConfigFromConf(cfg TLSClientConfig) (*tls.Config, error) {
    // createTLSConfig creates tls.Config based on TLSConfig.
    // It handles one-way and mutual TLS authentication, and TLS disabling.
    var tlsConf *tls.Config = nil // initialize tlsConf to nil, which means TLS is disabled by default

    if len(cfg.CAFile) != 0 { // if CAFile is configured, then enable TLS
        var err error
        if cfg.CertFile != "" && cfg.KeyFile != "" {
            // if CertFile and KeyFile are both configured, then use mutual TLS authentication
            tlsConf, err = ClientTLSConfVerity(cfg.CAFile, cfg.CertFile,
                cfg.KeyFile, "")
        } else {
            // otherwise, only CAFile is configured, use one-way TLS authentication, only verify server certificate
            tlsConf, err = ClientTslConfVerityServer(cfg.CAFile)
        }
        if err != nil {
            return nil, err
        }
        if tlsConf != nil {
            tlsConf.InsecureSkipVerify = cfg.InsecureSkipVerify
        }
    }
    // if cfg.TLSConfig.CAFile is empty, then tlsConf remains nil, which means TLS is disabled
    return tlsConf, nil
}
```

#### 2. Redis 客户端

抽离 TLSClientConf 之后，只需要在 redis 客户端配置中添加字段引用即可：

```go
// Config define redis config
type Config struct {
    Address          string
    Password         string
    Database         string
    // ...省略
    // tls config
    TLSConfig commonSSL.TLSClientConfig
}
```

通过 TLS 配置，读取指定路径下的证书，构建 tls.Config，在构建 redis 客户端时 Options 增加 TLS 配置：

```go
// ...
tlsConfig, err := commonSSL.NewTLSConfigFromConf(cfg.TLSConfig)
// ...
option := &redis.Options{
    // 省略...
    TLSConfig: tlsConfig,
}
client = NewClient(option)
```

#### 3. Redisstore 客户端修改

`src/storage/dal/redis/redis_store.go`，NewRedisStore和NewRedisStoreWithSentinel在参数上都不支持，增加TLS参数支持

```go
func NewRedisStore(size int, network, address, password string, tlsConf commonSSL.TLSClientConfig,
    keyPairs ...[]byte) (RedisStore, error) {
    // NewRediStore 从参数上直接不支持TLS，需要参考NewRedisStoreWithSentinel，改用Dial的方式，可以传入TLS配置
    // store, err := redistore.NewRediStore(size, network, address, password, keyPairs...)
}
func NewRedisStoreWithSentinel(address []string, size int, masterName, network, password string, sentinelPwd string,
    tlsConf commonSSL.TLSClientConfig, keyPairs ...[]byte) (RedisStore, error) {
    tls , err := commonSSL.NewTLSConfigFromConf(tlsConf)
    // ... 省略
    sntnl := &sentinel.Sentinel{
        // ... 省略
        Dial: func(addr string) (redis.Conn, error) {
            timeout := time.Second
            return redis.Dial(network, addr,
                // ...
                // 增加使用 tls
                redis.DialUseTLS(tls != nil),
                redis.DialTLSConfig(tls),
            )
        },
    }

}
```

WebServer 调用构建 redisstore 部分，需要增加传入TLS参数：

```go
if webSvr.Config.Redis.MasterName == "" {
    // MasterName 为空，表示使用直连redis 。 使用Host,Port 做链接redis参数
    service.Session, redisErr = redis.NewRedisStore(10, "tcp", webSvr.Config.Redis.Address,
        webSvr.Config.Redis.Password, webSvr.Config.Redis.TLSConf, []byte("secret"))
} else {
    // MasterName 不为空，表示使用哨兵模式的redis。MasterName 是Master标记
    address := strings.Split(webSvr.Config.Redis.Address, ";")
    service.Session, redisErr = redis.NewRedisStoreWithSentinel(address, 10, webSvr.Config.Redis.MasterName, "tcp",
        webSvr.Config.Redis.Password, webSvr.Config.Redis.SentinelPassword, webSvr.Config.Redis.TLSConf, []byte("secret"))
}
```

#### 4. viper增加读取yaml配置文件中的证书路径字段

```go
func Redis(prefix string) (redis.Config, error) {
	return redis.Config{
		TLSConfig: ssl.TLSClientConfig{
			InsecureSkipVerify: parser.getBool(prefix + ".tls.insecureSkipVerify"),
			CertFile:           parser.getString(prefix + ".tls.certFile"),
			KeyFile:            parser.getString(prefix + ".tls.keyFile"),
			CAFile:             parser.getString(prefix + ".tls.caFile"),
		},
	}, nil
}
```

#### 5. `script/init.py` 初始化配置文件脚本

增加初始化配置文件支持指定证书：

```sh
--redis_certfile     ./redis.cert \\
--redis_keyfile      ./redis.key \\
--redis_cafile       ./redis-ca.crt \\
--redis_skipverify   true \\
```

#### 6. Chart 修改

cmdb 不同服务可以连接不同的 redis，参考 gseCert，在 `values.yaml` 中增加一个 redisCert，分别写不同服务依赖的 redis 的 Cert，如：

```yaml
redisCert:
  redis:
    ca: ""
    cert: ""
    key: ""
  snapshotRedis:
    ca: ""
    cert: ""
    key: ""
  // ...
```

新增 configmap，用户存放 redis 的证书，只有当 redisCert 中有值才写该文件，如：

```yaml
{{- range $redisType, $prefix := $redisTypes }}
{{- $certData := index $.Values.redisCert $redisType }}
{{- if or $certData.ca $certData.cert $certData.key }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bk-cmdb.fullname" $ }}-{{ $prefix }}-certs
data:
  {{- if $certData.ca }}
  {{ $prefix }}.ca: {{ $certData.ca | b64dec | quote }}
  {{- end }}
  {{- if $certData.cert }}
  {{ $prefix }}.cert: {{ $certData.cert | b64dec | quote }}
  {{- end }}
  {{- if $certData.key }}
  {{ $prefix }}.key: {{ $certData.key | b64dec | quote }}
  {{- end }}
---
{{- end }}
{{- end }} 
```

在 `values.yaml` redis 添加证书的路径，固定路径和文件名

```yaml
redis:
  redis:
    tls:
      skipVerify: true
      # redis 使用的证书路径，如:/data/cmdb/cert/redis-ca.crt
      caFile: "/data/cmdb/cert/redis-ca.crt"
      certFile: "/data/cmdb/cert/redis.cert"
      keyFile: "/data/cmdb/cert/redis.key"
  snap:
    tls:
      skipVerify: true
      caFile: "/data/cmdb/cert/redis-snap-ca.crt"
      certFile: "/data/cmdb/cert/redis-snap.cert"
      keyFile: "/data/cmdb/cert/redis-snap.key"
```

`_helpers.tpl` 可以先定义好证书的 volume 和 volueMount：

```yaml
{{- define "cmdb.redis.certVolumeMount" -}}
{{- if or .Values.redisCert.redis.ca .Values.redisCert.redis.key .Values.redisCert.redis.cert }}
- name: redis-certs
  mountPath: {{ .Values.certPath }}/redis
{{- end }}
{{- end -}}

{{- define "cmdb.redis.certVolume" -}}
{{- if or .Values.redisCert.redis.ca .Values.redisCert.redis.key .Values.redisCert.redis.cert }}
- name: redis-certs
  configMap:
    name: {{ template "bk-cmdb.fullname" . }}-redis-certs
{{- end }}
{{- end -}}
```

在依赖redis服务的 deployment 中增加挂在这个 configmap，挂载到values.yaml中使用的路径，这部分在判断在多个deployment可能都需要使用，可以 `_helpers.tpl` 创建好

```yaml
volumeMounts:
  {{- include "cmdb.redis.certVolumeMount" . | nindent 10 }}
volumes:
  {{- include "cmdb.redis.certVolume" . | nindent 6 }}
```

在 `adminserver` 的 `configmap.yaml` 增加配置 tls 配置，使用 values：

```yaml
redis.yaml: |-  
  reids: 
      tls:
        insecureSkipVerify: {{ .Values.redis.redis.tls.insecureSkipVerify }}
      {{- if .Values.redisCert.redis.ca }}
        caFile: {{ .Values.redis.redis.tls.caFile }}
      {{- end }}
      {{- if and .Values.redisCert.redis.cert .Values.redisCert.redis.key }}
        certFile: {{ .Values.redis.redis.tls.certFile }}
        keyFile: {{ .Values.redis.redis.tls.keyFile }}
      {{- end }}
```
