### ISSUE TITLE
cmdb_migrate镜像没有，还有连接其他平台的接口要怎么获取

### ISSUE THREAD

**Issue by 13567436138** [Tencent/bk-cmdb#8423]
```
migrate:
  enabled: true
  image:
    repository: blueking/cmdb_migrate
    tag:

bkPaasUrl: http://paas.example.com
## @param bkIamApiUrl bk-iam backend url
##
bkIamApiUrl: http://bkiam-web
## @param bkComponentApiUrl esb url
##
bkComponentApiUrl: http://bkapi.paas.example.com
## @param bkLoginApiUrl bk-login url
##
bkLoginApiUrl: http://bk-login-web
## @param bkNodemanUrl bk-nodeman url
##
bkNodemanUrl: http://apps.paas.example.com/bk--nodeman

## @param bkApigatewayName apigateway name for cmdb
##
bkApigatewayName: "bk-cmdb"

# 蓝鲸 GSE API Gateway url
bkGseApiGatewayUrl: "http://bkapi.example.com"

# 蓝鲸 Notice API Gateway url
bkNoticeApiGatewayUrl: "http://bkapi.example.com"

## 蓝鲸共享资源URL
bkSharedResUrl:
```
